name: Tests

on:
  push:
    branches:
      - 'main'

  pull_request:
    types: [ opened, reopened, synchronize, labeled ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Run tests
        run: poetry run pytest --cov=hgraph -cov-report=xml
